spring:
  application:
    name: kazinsight-monolith
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/kazinsight-monolith}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
