spring:
  application:
    name: kazinsight-monolith
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/kazinsight-monolith}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

image:
  link-constructor: ${IMAGE_LINK_CONSTRUCTOR:http://localhost:8080/images/}