-- Таблица Enrollment
CREATE TABLE enrollment (
                            tour_id BIGINT NOT NULL,
                            user_id BIGINT NOT NULL,
                            UNIQUE (user_id, tour_id)
);

-- Таблица Favorite
CREATE TABLE favorite (
                          place_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          UNIQUE (user_id, place_id)
);

-- Таблица Images
CREATE TABLE images (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        place_id BIGINT,
                        tour_id BIGINT,
                        link VARCHAR(255)
);

-- Таблица Places
CREATE TABLE places (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        latitude FLOAT(53),
                        longitude FLOAT(53),
                        created_at TIMESTAMP(6),
                        creator_id BIGINT,
                        updated_at TIMESTAMP(6),
                        created_by VARCHAR(255),
                        description VARCHAR(255),
                        name VARCHAR(255),
                        updated_by VARCHAR(255)
);

-- Таблица Reviews
CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         rating FLOAT(53),
                         created_at TIMESTAMP(6),
                         creator_id BIGINT,
                         place_id BIGINT,
                         updated_at TIMESTAMP(6),
                         created_by VARCHAR(255),
                         text VARCHAR(255),
                         updated_by VARCHAR(255)
);

-- Таблица Tours
CREATE TABLE tours (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       price FLOAT(53),
                       created_at TIMESTAMP(6),
                       end_date TIMESTAMP(6),
                       start_date TIMESTAMP(6),
                       updated_at TIMESTAMP(6),
                       created_by VARCHAR(255),
                       description VARCHAR(255),
                       name VARCHAR(255),
                       updated_by VARCHAR(255)
);

-- Таблица Users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP(6),
                       updated_at TIMESTAMP(6),
                       created_by VARCHAR(255),
                       email VARCHAR(255),
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       password VARCHAR(255),
                       role VARCHAR(255) CHECK (role IN ('ADMIN', 'USER')),
                       updated_by VARCHAR(255)
);

-- Ограничения внешних ключей
ALTER TABLE enrollment
    ADD CONSTRAINT FK_enrollment_user FOREIGN KEY (user_id) REFERENCES users,
    ADD CONSTRAINT FK_enrollment_tour FOREIGN KEY (tour_id) REFERENCES tours;

ALTER TABLE favorite
    ADD CONSTRAINT FK_favorite_place FOREIGN KEY (place_id) REFERENCES places,
    ADD CONSTRAINT FK_favorite_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE images
    ADD CONSTRAINT FK_images_place FOREIGN KEY (place_id) REFERENCES places,
    ADD CONSTRAINT FK_images_tour FOREIGN KEY (tour_id) REFERENCES tours;

ALTER TABLE places
    ADD CONSTRAINT FK_places_creator FOREIGN KEY (creator_id) REFERENCES users;

ALTER TABLE reviews
    ADD CONSTRAINT FK_reviews_creator FOREIGN KEY (creator_id) REFERENCES users,
    ADD CONSTRAINT FK_reviews_place FOREIGN KEY (place_id) REFERENCES places;
